# ~/.config/starship.toml

# è¾“å‡ºåæ¢è¡Œ
add_newline = true

# æ˜¾ç¤ºæ—¶é—´
[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "+8"
time_range = "10:00:00-14:00:00"

#symbol = "ğŸš€"
[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

# åå°ä»»åŠ¡
[jobs]
symbol = "+ "
threshold = 4

# Git åˆ†æ”¯å›¾æ ‡
[git_branch]
symbol = "ğŸ”± "
